import { awscdk, TextFile, DependencyType } from 'projen';
import { GithubCredentials, workflows } from 'projen/lib/github';
import { NpmAccess, UpgradeDependenciesSchedule } from 'projen/lib/javascript';
const cdkCliVersion = '2.1029.2';
const minNodeVersion = '20.0.0';
const devNodeVersion = '20.19.0';
const workflowNodeVersion = '20.x';
const jsiiVersion = '^5.8.0';
const cdkVersion = '2.85.0'; // Minimum CDK Version Required
const minProjenVersion = '0.98.10'; // Does not affect consumers of the library
const minConstructsVersion = '10.0.5'; // Minimum version to support CDK v2 and does affect consumers of the library
const devConstructsVersion = '10.0.5'; // Pin for local dev/build to avoid jsii type conflicts
const project = new awscdk.AwsCdkConstructLibrary({
  author: 'Jayson Rawlins',
  description: 'A GitHub Action that creates a CDK diff for a pull request.',
  keywords: ['aws', 'cdk', 'github', 'action', 'diff', 'pull request'],
  authorAddress: 'JaysonJ.Rawlins@gmail.com',
  packageName: '@jjrawlins/cdk-diff-pr-github-action',
  minNodeVersion: minNodeVersion,
  stability: 'experimental',
  cdkVersion: cdkVersion,
  cdkCliVersion: cdkCliVersion,
  projenVersion: `^${minProjenVersion}`,
  defaultReleaseBranch: 'main',
  majorVersion: 1, // Bump to 1.0.0 for StackSet and dual-mode API features
  license: 'Apache-2.0',
  jsiiVersion: jsiiVersion,
  name: '@jjrawlins/cdk-diff-pr-github-action',
  projenrcTs: true,
  repositoryUrl: 'https://jjrawlins@github.com/JaysonRawlins/cdk-diff-pr-github-action.git',
  githubOptions: {
    projenCredentials: GithubCredentials.fromApp({
      appIdSecret: 'PROJEN_APP_ID',
      privateKeySecret: 'PROJEN_APP_PRIVATE_KEY',
    }),
    mergify: false,
    pullRequestLintOptions: {
      semanticTitleOptions: {
        types: [
          'feat',
          'fix',
          'docs',
          'style',
          'refactor',
          'perf',
          'test',
          'chore',
          'revert',
          'ci',
          'build',
          'deps',
          'wip',
          'release',
        ],
      },
    },
  },
  depsUpgrade: true,
  depsUpgradeOptions: {
    workflowOptions: {
      schedule: UpgradeDependenciesSchedule.expressions(['0 9 * * 1']),
    },
  },
  peerDeps: [
    `aws-cdk-lib@>=${cdkVersion} <3.0.0`,
    `constructs@>=${minConstructsVersion} <11.0.0`,
  ],
  deps: [ // Does affect consumers of the library
    'crypto-js',
    'lodash',
    '@aws-sdk/client-cloudformation',
  ],
  devDeps: [ // Does not affect consumers of the library
    `aws-cdk@${cdkCliVersion}`,
    `aws-cdk-lib@${cdkVersion}`,
    '@aws-sdk/types',
    '@types/node',
    '@types/lodash',
    'projen',
  ],
  bundledDeps: [
    '@aws-sdk/client-cloudformation',
    '@types/js-yaml',
    'js-yaml',
    'lodash.merge',
    '@types/crypto-js',
    'crypto-js',
    'lodash',
  ],
  gitignore: [
    'cdk.out',
    'cdk.out/*',
    'assets',
    'cdk.context.json',
    'tsconfig.json',
    '.dccache',
    '.yalc',
  ],
  npmAccess: NpmAccess.PUBLIC,
  releaseToNpm: true,
  npmTrustedPublishing: true, // Enable npm Trusted Publishing via OIDC - eliminates need for NPM_TOKEN
  publishToPypi: {
    distName: 'jjrawlins-cdk-diff-pr-github-action',
    module: 'jjrawlins_cdk_diff_pr_github_action',
    trustedPublishing: true,
  },
  publishToNuget: {
    dotNetNamespace: 'JJRawlins.CdkDiffPrGithubAction',
    packageId: 'JJRawlins.CdkDiffPrGithubAction',
    trustedPublishing: true,
  },
  publishToGo: {
    moduleName: 'github.com/JaysonRawlins/cdk-diff-pr-github-action',
    packageName: 'cdkdiffprgithubaction',
  },
});

// Add Yarn resolutions to ensure patched transitive versions
project.package.addField('resolutions', {
  'brace-expansion': '1.1.12',
  'form-data': '^4.0.4',
  '@eslint/plugin-kit': '^0.3.4',
  'aws-cdk-lib': `>=${cdkVersion} <3.0.0`,
  // Pin constructs for local dev/build to a single version to avoid jsii conflicts
  'constructs': devConstructsVersion,
  'projen': `>=${minProjenVersion} <1.0.0`,
});

// Allow Node 20+ for consumers (CDK constructs work on any modern Node).
project.package.addField('engines', {
  node: `>=${minNodeVersion}`,
});

new TextFile(project, '.tool-versions', {
  lines: [
    '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
    `nodejs ${devNodeVersion}`,
    'yarn 1.22.22',
  ],
});

// Allow importing projen from devDependencies in source files.
// projen is a build-time dependency (consumers provide their own projen).
project.eslint?.addOverride({
  files: ['src/**/*.ts'],
  rules: {
    'import/no-extraneous-dependencies': ['error', {
      devDependencies: true,
      optionalDependencies: false,
      peerDependencies: true,
    }],
  },
});

// Ensure 'constructs' is only a peer dependency (avoid duplicates that cause jsii conflicts)
project.deps.removeDependency('constructs');
project.deps.addDependency(`constructs@>=${minConstructsVersion} <11.0.0`, DependencyType.PEER);

project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.upgrade.permissions.id-token', 'write');
project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.upgrade.permissions.packages', 'write');
project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.upgrade.permissions.pull-requests', 'write');
project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.upgrade.permissions.contents', 'write');
project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.upgrade.steps.1.with.node-version', workflowNodeVersion);

project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.pr.permissions.id-token', 'write');
project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.pr.permissions.packages', 'write');
project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.pr.permissions.pull-requests', 'write');
project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.pr.permissions.contents', 'write');

// Add auto-merge step to upgrade-main workflow (step index 6, after PR creation)
project.github!.tryFindWorkflow('upgrade-main')!.file!.addOverride('jobs.pr.steps.6', {
  name: 'Enable auto-merge',
  if: "steps.create-pr.outputs.pull-request-number != ''",
  run: 'gh pr merge --auto --squash "${{ steps.create-pr.outputs.pull-request-number }}"',
  env: {
    GH_TOKEN: '${{ steps.generate_token.outputs.token }}',
  },
});

/**
 * For the build job, we need to be able to read from packages and also need id-token permissions for OIDC to authenticate to the registry.
 * This is needed to be able to install dependencies from GitHub Packages during the build.
 */
project.github!.tryFindWorkflow('build')!.file!.addOverride('jobs.build.permissions.id-token', 'write');
project.github!.tryFindWorkflow('build')!.file!.addOverride('jobs.build.permissions.packages', 'read');

/**
 * Fix checkout to use SHA instead of branch ref (survives branch deletion after automerge).
 * When automerge deletes the head branch before workflow jobs complete, using the branch ref fails.
 * The commit SHA persists even after branch deletion.
 */
const buildWorkflow = project.github!.tryFindWorkflow('build')!;

// Override main build job checkout (step index 0)
buildWorkflow.file!.addOverride('jobs.build.steps.0.with.ref', '${{ github.event.pull_request.head.sha }}');
buildWorkflow.file!.addOverride('jobs.build.steps.1.with.node-version', workflowNodeVersion);

// Override self-mutation job checkout (step index 1, after token generation)
buildWorkflow.file!.addOverride('jobs.self-mutation.steps.1.with.ref', '${{ github.event.pull_request.head.sha }}');

// Override package-js job checkout (step index 3)
buildWorkflow.file!.addOverride('jobs.package-js.steps.3.with.ref', '${{ github.event.pull_request.head.sha }}');
buildWorkflow.file!.addOverride('jobs.package-js.steps.0.with.node-version', workflowNodeVersion);

// Override package-python job checkout (step index 4, after setup-node + setup-python)
buildWorkflow.file!.addOverride('jobs.package-python.steps.4.with.ref', '${{ github.event.pull_request.head.sha }}');
buildWorkflow.file!.addOverride('jobs.package-python.steps.0.with.node-version', workflowNodeVersion);

// Override package-dotnet job checkout (step index 4, after setup-node + setup-dotnet)
buildWorkflow.file!.addOverride('jobs.package-dotnet.steps.4.with.ref', '${{ github.event.pull_request.head.sha }}');
buildWorkflow.file!.addOverride('jobs.package-dotnet.steps.0.with.node-version', workflowNodeVersion);

// Override package-go job checkout (step index 4, after setup-node + setup-go)
buildWorkflow.file!.addOverride('jobs.package-go.steps.4.with.ref', '${{ github.event.pull_request.head.sha }}');
buildWorkflow.file!.addOverride('jobs.package-go.steps.0.with.node-version', workflowNodeVersion);

/** * For the release jobs, we need to be able to read from packages and also need id-token permissions for OIDC to authenticate to the registry.
*/
const releaseWorkflow = project.github!.tryFindWorkflow('release')!;
releaseWorkflow.file!.addOverride('jobs.release.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release.permissions.packages', 'read');
releaseWorkflow.file!.addOverride('jobs.release.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release.steps.2.with.node-version', workflowNodeVersion);
releaseWorkflow.file!.addOverride('jobs.release_github.steps.0.with.node-version', workflowNodeVersion);

releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.packages', 'read');
releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.contents', 'write');

// Override node-version to 24 for npm trusted publishing (requires npm 11.5.1+)
// This only affects the release_npm job, not the project's minNodeVersion
releaseWorkflow.file!.addOverride('jobs.release_npm.steps.0.with.node-version', '24');
// Add --ignore-engines to yarn install since Node 24 is outside the engines range (20.x)
releaseWorkflow.file!.addOverride('jobs.release_npm.steps.4.run', 'cd .repo && yarn install --check-files --frozen-lockfile --ignore-engines');

// PyPI release permissions and node version
releaseWorkflow.file!.addOverride('jobs.release_pypi.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_pypi.permissions.packages', 'read');
releaseWorkflow.file!.addOverride('jobs.release_pypi.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_pypi.steps.0.with.node-version', workflowNodeVersion);

// NuGet release permissions and node version
releaseWorkflow.file!.addOverride('jobs.release_nuget.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_nuget.permissions.packages', 'read');
releaseWorkflow.file!.addOverride('jobs.release_nuget.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_nuget.steps.0.with.node-version', workflowNodeVersion);

// Go release permissions and node version
releaseWorkflow.file!.addOverride('jobs.release_golang.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_golang.permissions.packages', 'read');
releaseWorkflow.file!.addOverride('jobs.release_golang.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_golang.steps.0.with.node-version', workflowNodeVersion);

// Replace GO_GITHUB_TOKEN PAT with GitHub App installation token for Go module publishing
// Step 10: clear old Release step fields and repurpose as token generation
releaseWorkflow.file!.addOverride('jobs.release_golang.steps.10.name', 'Generate token');
releaseWorkflow.file!.addOverride('jobs.release_golang.steps.10.id', 'generate_token');
releaseWorkflow.file!.addOverride('jobs.release_golang.steps.10.uses', 'actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5');
releaseWorkflow.file!.addOverride('jobs.release_golang.steps.10.with', {
  'app-id': '${{ secrets.PROJEN_APP_ID }}',
  'private-key': '${{ secrets.PROJEN_APP_PRIVATE_KEY }}',
});
// Remove old Release step fields from step 10
releaseWorkflow.file!.addDeletionOverride('jobs.release_golang.steps.10.env');
releaseWorkflow.file!.addDeletionOverride('jobs.release_golang.steps.10.run');
// Step 11: actual release using the App token
releaseWorkflow.file!.addOverride('jobs.release_golang.steps.11', {
  name: 'Release',
  env: {
    GIT_USER_NAME: 'github-actions[bot]',
    GIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com',
    GITHUB_TOKEN: '${{ steps.generate_token.outputs.token }}',
  },
  run: [
    // publib constructs https://<token>@github.com/... which works for PATs but not GitHub App tokens.
    // App tokens require the x-access-token: username prefix.
    'git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://${GITHUB_TOKEN}@github.com/"',
    'npx -p publib@latest publib-golang',
  ].join('\n'),
});

// Dependabot: disable version update PRs (projen handles upgrades via upgrade-main workflow)
// Security alerts remain active at the repo level
new TextFile(project, '.github/dependabot.yml', {
  lines: [
    '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
    'version: 2',
    'updates:',
    '  - package-ecosystem: npm',
    '    directory: /',
    '    schedule:',
    '      interval: weekly',
    '    open-pull-requests-limit: 0',
    '  - package-ecosystem: github-actions',
    '    directory: /',
    '    schedule:',
    '      interval: weekly',
    '    open-pull-requests-limit: 0',
  ],
});

// Prevent release workflow from triggering on Go module commits
releaseWorkflow.file!.addOverride('on.push.paths-ignore', [
  'cdkdiffprgithubaction/**',
]);

// Dependency review on PRs — blocks merge if new high/critical vulnerabilities are introduced
// Works with existing Dependabot security updates to create a merge gate
const securityWorkflow = project.github!.addWorkflow('security');
securityWorkflow.on({
  pullRequest: {
    branches: ['main'],
  },
});
securityWorkflow.addJobs({
  'dependency-review': {
    name: 'Dependency Review',
    runsOn: ['ubuntu-latest'],
    permissions: {
      contents: workflows.JobPermission.READ,
      pullRequests: workflows.JobPermission.WRITE,
    },
    steps: [
      {
        name: 'Checkout',
        uses: 'actions/checkout@v5',
      },
      {
        name: 'Dependency Review',
        uses: 'actions/dependency-review-action@v4',
        with: {
          'fail-on-severity': 'high',
          'comment-summary-in-pr': 'always',
        },
      },
    ],
  },
});

project.synth();


